<?php

namespace InitigerCo\Bundle\SiteBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiteRepository extends EntityRepository
{
    public function findSiteByDomains($domains = [])
    {
        $qb = $this->createQueryBuilder('s');

        return $qb->where($qb->expr()->in('status', $domains))
            ->getQuery()
            ->getResult();
    }
}
